backend:
  name: github
  repo: template01/netlifycmstest
  branch: master # Branch to update

#publish_mode: editorial_workflow
media_folder: "static/images/"

collections:
- label: "Blog"
  name: "blog"
  folder: "content/_posts/blog"
  create: true
  fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Featured Image", name: "thumbnail", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}
